### ISSUE TITLE
Not possible to compile the most recent version

### ISSUE THREAD

**Issue by DeceptedPar** [ItzFireable/VsCamellia#10]
I dont know what to do
-
![image](https://user-images.githubusercontent.com/64243677/127036838-3d43dea5-8651-40f1-925d-a8f4b449ebb1.png)

**Comment by gummybear17** [comment]
you can compile it just delete where it has the SKIP_STEP_LIMiT or here look on my video [SKIP_STEP_LIMIT help ](https://www.youtube.com/watch?v=4fFx5iqOPcA)
